language: node_js
node_js:
  - "node"

deploy:
  app: acebook-stars-frontend
  provider: heroku
  on:
    branch: master
  api_key:
    secure: JKuZbkbFQk/Vei/5eipRfX5E+TYEjyjiyNaBFBesgPD0E3EVuCx+vUXLMeA0sN/4PXWnKzHWCMJcvcHhpM8v11PTmo/qfs2Pc7tueM0AErR8yFqa/F01HaUa9P4oyM9MaZhUTBfyRNMYvs0C6woicvM4FW3QsLM3EPS5Cg4idfVTMurPNTdgR3zp9ZmA6B7FPIGH+71kDHPgennuLvWXQyZrN70y56DL8UO6C35A0i3S7BpRrKydkAqKBtCP9WxqRNZpLYtJL+TBzAu+DUEf4fdMDivZX5W1xGiciC3Fl4B33ovb3ZV4DwykP9BQRakVSC/e3nAzlP4Pgc2arkaIkdiYgrNm1WTjFTR9k34N5Bjnt9PllsJQ8TXx8jFiZ913WU5yEBEIlytzH/TfqVp3tpm0zc4VALFwVVMFffN8ey6qeA/HpSPY+ibx4yjfcogHDMKlbbdfzCImuVqKxP+YqTcycM0wXiKbXaAt47QI3ic8gOnxW5y66lkbkJCg68hVRmHxUI/CiIUFL/dgIvW4AXp4LS8l+GzPBB8EEAzIlGSu9jQp0RN5nJIcCIsi7/brQrkRpYG62LBF/iW8zcHckqbYmMjgUMYeHLa/OiGeiardgwv5rLpk9P+1r5fAL+rWyv9Dq0Uo8ZiPnqLuu5Ylsjjj5m4dDPbGFFvh8HTZmvs=

script:
  - npm build
